version: '3.8'
services:
  db:
    image: postgres:15
    container_name: clinic-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
