version: '3.8'

services:
  clinic-app:
    build: .
    container_name: clinic-app
    ports:
      - '3000:3000'
    depends_on:
      - clinic-postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_URL=${API_URL}
    volumes:
      - .:/app
    command: npm run start:dev

  clinic-postgres:
    image: postgres:15
    container_name: clinic-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clinicdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - clinic-postgres

volumes:
  pgdata:
